### ISSUE TITLE
"Privacy Policy" link in setting is broken

### ISSUE THREAD

**Issue by DoNutsLise** [redDwarf03/my_bismuth_wallet#3]
v1.0.26
Clicking on Privacy Policy opens 404 page

**Comment by redDwarf03** [comment]
Could you install the 1.0.30 please. Thx

**Comment by DoNutsLise** [comment]
The latest version in Google play store is 1.0.26

**Comment by redDwarf03** [comment]
Good point! 1.0.30 is not in the google store. I delete old policy too early...
The policy is available at https://hypernodes.bismuth.live/?page_id=2565
