### ISSUE TITLE
Back up secret Phrase error

### ISSUE THREAD

**Issue by DoNutsLise** [redDwarf03/my_bismuth_wallet#4]
v1.0.26:
In settings clicking on "Backup Secret Phrase" opens a widget requesting to enter the pincode.
If you don't enter a pincode and click "back" button on the phone - Error "platformException" is thrown.
Let me know if it's not reproducible - I'll upload more data/logs

**Comment by redDwarf03** [comment]
Could you say me if we have the same issue with last version please 1.0.30

**Comment by DoNutsLise** [comment]
The latest version in Google Play store is 1.0.26, but I'm sure the same problem will exist in 1.0.30, because the page is broken in your repo: https://github.com/redDwarf03/my_bismuth_wallet/blob/master/Privacy%20Policy.md
